version: '3'
services:
  db:
    image: postgres:11.4-alpine
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - ./pg_data:/var/lib/postgresql/data/pgdata
    evvironment:
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: docker_test
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always 
  app:
    image: evgendemidovs/myapp:alpine1
    container_name: application
    ports: 
      - 3000:3000 
    environment:
      POSTGRES_HOST: db
    restart: always
    links:
      - db 
  nginx: 
    image: nginx:1.17.2-alpine
    container_name: nginx
    volumes: 
      - ./default.conf:/etc/nginx/conf.d/default.conf
    links:
      - app 
    
